### ISSUE TITLE
Add section for garbage collectors

### ISSUE THREAD

**Issue by segeljakt** [Kixiron/rust-langdev#12]
Garbage collectors can be useful inside compilers to manage data structures like the AST both during compilation and evaluation. Here are the ones I have tried:

* [gc](https://crates.io/crates/gc)
* [shredder](https://crates.io/crates/shredder)
* [broom](https://crates.io/crates/broom)

**Comment by Kixiron** [comment]
I don't know when I'll get around to this, but I'd love a pr adding them!

**Comment by Kixiron** [comment]
Added the section, thanks!
