### ISSUE TITLE
Ropey isn't well suited to language development.

### ISSUE THREAD

**Issue by cessen** [Kixiron/rust-langdev#17]
I just stumbled on this today, and noticed that you've listed [ropey](https://github.com/cessen/ropey) under the string handling section.  And although I'm grateful to see my crate in a list of recommendations, in this case it's misplaced.

Ropey was not designed for, and is not well suited to, the kind of work that compilers, interpreters, language servers, etc. do.  At best, it would just add a bunch of unneeded bloat, and at worst it would needlessly complicate the code and harm performance.

Ropey's tradeoffs and complexity are really only justified for projects that need to make frequent edits to medium-to-large sized texts (e.g. text editors).

**Comment by Kixiron** [comment]
Language servers have pretty much the same needs as text editors since editors are the ones feeding text diffs into them, ropey is used quite a bit within lsps

**Comment by cessen** [comment]
Oh, interesting.  I assumed that most (all?) language servers would utilize compiler/interpreter internals, which typically expect contiguous text.  In which case you would just end up converting the rope to a contiguous string for every query anyway, at which point the rope becomes an unnecessary intermediary: if you're going to be copying all of the data anyway, you might as well just apply the diff directly as you do the copy.

But I very well could be missing something.

**Comment by Kixiron** [comment]
Language servers generally have to be written from scratch since their load is so different from a normal compiler (focus on fast response times above all else, no codegen requirements, etc.) so that's generally a non-issue

**Comment by cessen** [comment]
Ah, fair enough.  Never mind, then!

**Comment by ratmice** [comment]
@cessen I thought it might be worth giving you a concrete case where ropey undoubtedly helps,
LSP might not just send a diff but it may send multiple diffs, which need to be applied in sequence.

For a concrete instance when you search & replace all instances of some word, it is worthwhile to apply these sequential diffs to a rope rather than a string even if you end up converting it to a string eventually for some reason.

**Comment by cessen** [comment]
@ratmice Thanks for the use case example.

The main reason I filed this issue is because I get issues filed against Ropey from time to time from people who are trying to use it in compilers/interpreters/etc., but run into things they need/want that are out of scope for Ropey.  And it isn't fun to repeatedly tell people who have already sunk time into integrating Ropey into their code base that they probably shouldn't have used Ropey in the first place.

So I mainly just don't want Ropey being on this list to make that problem worse.
