### ISSUE TITLE
Add cilk to Codegen

### ISSUE THREAD

**Issue by playXE** [Kixiron/rust-langdev#2]
[cilk](https://github.com/maekawatoshiki/cilk) is compiler infrastructure influenced by LLVM written in Rust

**Comment by Kixiron** [comment]
It says it's a toy right now, is it ready to be presented as something to be seriously used?

**Comment by playXE** [comment]
I think so, there is [minilang](https://github.com/maekawatoshiki/cilk/blob/master/minilang) and it seems to showcase more features than Cranelift's simplejit-demo

**Comment by Kixiron** [comment]
Added it, thanks!
